### ISSUE TITLE
Data files?

### ISSUE THREAD

**Issue by mlavista** [sudongqi/TensorFlow_ChatBot#6]
I'd love to try this out - but your scripts are referencing some missing data files:

OSError: [Errno 2] No such file or directory: 'bbt_data/p300_h512_x1'

Do you have a link to them?

**Comment by sudongqi** [comment]
p300_h512_x1 is the name of the trained model (which is determined by the configuration of the model).

model_name = "p" + str(projection_size) + "_h" + str(hidden_size) + "_x" + str(num_layers)
save_path = file_name + "/" + model_name

This design is bad but it's due to the limitation of the old TensorFlow. I will upgrade it if I have the time.
